from __future__ import annotations

from court_hrms.reporting.report_dtos import (
    IndividualProfileReport,
    LeaveHistoryReport,
    SeniorityListReport,
)
from court_hrms.utils.report_utils import report_date, safe_text


REPORT_CSS = """
body { font-family: "Times New Roman", serif; font-size: 10pt; color: #111827; }
.header { text-align: center; border-bottom: 2px solid #0b1f3a; padding-bottom: 8px; margin-bottom: 12px; }
.court { font-size: 16pt; font-weight: bold; letter-spacing: 0; color: #0b1f3a; }
.system { font-size: 11pt; font-weight: bold; color: #374151; }
.title { font-size: 13pt; font-weight: bold; margin-top: 8px; }
.meta { font-size: 9pt; color: #4b5563; margin-top: 4px; }
h2 { font-size: 11pt; color: #0b1f3a; border-bottom: 1px solid #c9a227; margin: 14px 0 6px; }
table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
th { background: #0b1f3a; color: #ffffff; font-weight: bold; }
th, td { border: 1px solid #9ca3af; padding: 5px; vertical-align: top; }
.label { width: 24%; font-weight: bold; background: #f3f4f6; }
.footer { border-top: 1px solid #9ca3af; margin-top: 16px; padding-top: 6px; font-size: 9pt; color: #4b5563; text-align: center; }
.policy { border: 1px solid #9ca3af; padding: 6px; background: #f9fafb; }
"""


def _base_document(title: str, generated_at, body: str) -> str:
    return f"""
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>{REPORT_CSS}</style>
</head>
<body>
<div class="header">
  <div class="court">DISTRICT COURT ORAKZAI</div>
  <div class="system">HUMAN RESOURCE MANAGEMENT SYSTEM</div>
  <div class="title">{safe_text(title)}</div>
  <div class="meta">Generated: {report_date(generated_at)}</div>
</div>
{body}
<div class="footer">Official HR record. Generated by District Court Orakzai HRMS.</div>
</body>
</html>
"""


def _detail_table(rows: list[tuple[str, object]]) -> str:
    cells = []
    for label, value in rows:
        cells.append(
            f'<tr><td class="label">{safe_text(label)}</td><td>{_value(value)}</td></tr>'
        )
    return f"<table>{''.join(cells)}</table>"


def _data_table(headers: list[str], rows: list[list[object]]) -> str:
    header_html = "".join(f"<th>{safe_text(header)}</th>" for header in headers)
    row_html = []
    for row in rows:
        row_html.append(
            "<tr>" + "".join(f"<td>{_value(value)}</td>" for value in row) + "</tr>"
        )
    if not rows:
        row_html.append(
            f'<tr><td colspan="{len(headers)}">No applicable records found.</td></tr>'
        )
    return f"<table><thead><tr>{header_html}</tr></thead><tbody>{''.join(row_html)}</tbody></table>"


def _value(value) -> str:
    if hasattr(value, "strftime"):
        return report_date(value)
    return safe_text(value)


def build_individual_profile_html(report: IndividualProfileReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Identity Details</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Father's Name", staff.get("father_name")),
    ("CNIC", staff.get("cnic")),
    ("Date of Birth", staff.get("date_of_birth")),
    ("Calculated Date of Retirement", staff.get("date_of_retirement")),
    ("Gender", staff.get("gender")),
    ("Religion", staff.get("religion")),
    ("Marital Status", staff.get("marital_status")),
    ("Qualification", staff.get("qualification")),
])}
<h2>Contact and Geographic Details</h2>
{_detail_table([
    ("Mobile Number", staff.get("mobile_number")),
    ("Email", staff.get("email")),
    ("Domicile", staff.get("domicile")),
    ("District", staff.get("district")),
    ("Tehsil", staff.get("tehsil")),
    ("Present Address", staff.get("present_address")),
    ("Permanent Address", staff.get("permanent_address")),
    ("Emergency Contact", staff.get("emergency_contact")),
])}
<h2>Current Service Details</h2>
{_detail_table([
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
    ("Employment Type", service.get("employment_type")),
    ("Employment Status", service.get("employment_status")),
    ("Date of First Appointment", service.get("date_first_appointment")),
    ("Date of Current Promotion", service.get("date_current_promotion")),
    ("Selection Merit Number", service.get("selection_merit_number")),
])}
<h2>Posting History</h2>
{_data_table(
    ["Station", "Start Date", "End Date", "Transfer Reason", "Current"],
    [
        [
            posting.get("station_name"),
            posting.get("start_date"),
            posting.get("end_date"),
            posting.get("transfer_reason"),
            "Yes" if posting.get("is_current") else "No",
        ]
        for posting in report.posting_history
    ],
)}
<h2>Leave Summary</h2>
{_data_table(
    ["Year", "Entitlement", "Availed", "Remaining"],
    [
        [
            summary.get("leave_year"),
            summary.get("entitlement_days"),
            summary.get("availed_days"),
            summary.get("remaining_days"),
        ]
        for summary in report.leave_summaries
    ],
)}
"""
    return _base_document("Individual Staff Profile", report.generated_at, body)


def build_leave_history_html(report: LeaveHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    selected = (
        "All Years" if report.selected_year is None else str(report.selected_year)
    )
    body = f"""
<h2>Staff Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
    ("Selected Year", selected),
])}
<h2>Leave Balance Summary</h2>
{_data_table(
    ["Year", "Entitlement", "Total Availed", "Remaining"],
    [
        [
            summary.get("leave_year"),
            summary.get("entitlement_days"),
            summary.get("availed_days"),
            summary.get("remaining_days"),
        ]
        for summary in report.summaries
    ],
)}
<h2>Leave History</h2>
{_data_table(
    ["Serial", "Start Date", "End Date", "Number of Days", "Reason", "Remarks", "Recorded Date"],
    [
        [
            index,
            row.get("start_date"),
            row.get("end_date"),
            row.get("days_availed"),
            row.get("reason"),
            row.get("remarks"),
            row.get("created_at"),
        ]
        for index, row in enumerate(report.history, start=1)
    ],
)}
"""
    return _base_document("Leave History", report.generated_at, body)


def build_seniority_list_html(report: SeniorityListReport) -> str:
    body = f"""
<h2>Report Summary</h2>
{_detail_table([
    ("Designation", report.designation),
    ("Ranked Staff", len(report.ranked)),
    ("Generated Date", report.generated_at),
])}
<h2>Seniority Policy</h2>
<div class="policy">{safe_text(report.policy_summary)}</div>
<h2>Ranked Seniority Table</h2>
{_data_table(
    [
        "Rank",
        "Personal Number",
        "Staff Name",
        "Father's Name",
        "BPS",
        "First Appointment",
        "Current Promotion",
        "Merit Number",
        "Date of Birth",
        "Current Posting",
    ],
    [
        [
            row.get("rank"),
            row.get("personal_number"),
            row.get("full_name"),
            row.get("father_name"),
            row.get("bps"),
            row.get("date_first_appointment"),
            row.get("date_current_promotion"),
            row.get("selection_merit_number"),
            row.get("date_of_birth"),
            row.get("current_posting"),
        ]
        for row in report.ranked
    ],
)}
"""
    return _base_document("Seniority List", report.generated_at, body)
