from __future__ import annotations

from court_hrms.reporting.report_dtos import (
    EmployeeDossierReport,
    IndividualProfileReport,
    LeaveHistoryReport,
    PostingHistoryReport,
    SeniorityListReport,
    ServiceBookExtractReport,
    TransferHistoryReport,
)
from court_hrms.utils.report_utils import report_date, safe_text


REPORT_CSS = """
body { font-family: "Times New Roman", serif; font-size: 10pt; color: #111827; }
.header { text-align: center; border-bottom: 2px solid #0b1f3a; padding-bottom: 8px; margin-bottom: 12px; }
.court { font-size: 16pt; font-weight: bold; letter-spacing: 0; color: #0b1f3a; }
.system { font-size: 11pt; font-weight: bold; color: #374151; }
.title { font-size: 13pt; font-weight: bold; margin-top: 8px; }
.meta { font-size: 9pt; color: #4b5563; margin-top: 4px; }
h2 { font-size: 11pt; color: #0b1f3a; border-bottom: 1px solid #c9a227; margin: 14px 0 6px; }
h3 { font-size: 10pt; color: #0b1f3a; margin: 8px 0 4px; }
table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
thead { display: table-header-group; }
tr { page-break-inside: avoid; }
th { background-color: #f3f4f6; color: #111827; font-weight: bold; }
th, td { border: 1px solid #9ca3af; padding: 5px; vertical-align: top; }
.label { width: 24%; font-weight: bold; background: #f3f4f6; }
.report-table { table-layout: fixed; page-break-inside: auto; }
.report-table th {
    border-color: #9ca3af;
    padding: 5px 4px;
    line-height: 1.15;
    white-space: nowrap;
    word-break: normal;
    overflow-wrap: normal;
    hyphens: none;
}
.report-table td {
    border-color: #cbd5e1;
    padding: 5px 4px;
    line-height: 1.2;
    white-space: normal;
    word-break: normal;
    overflow-wrap: break-word;
}
.report-table.compact th { font-size: 7.8pt; padding: 4px 3px; }
.report-table.compact td { font-size: 7.4pt; padding: 4px 3px; }
.report-table.standard th { font-size: 8.6pt; }
.report-table.standard td { font-size: 8.2pt; }
.report-table tr.alt td { background-color: #f8fafc; }
.report-table .empty-table { text-align: center; color: #4b5563; }
.report-table .number { text-align: center; }
.footer { border-top: 1px solid #9ca3af; margin-top: 16px; padding-top: 6px; font-size: 9pt; color: #4b5563; text-align: center; }
.policy { border: 1px solid #9ca3af; padding: 6px; background: #f9fafb; }
"""


WIDE_COLUMN_THRESHOLD = 8


HEADER_ALIASES = {
    "Serial": "Sr.",
    "Personal Number": "Personal No.",
    "Movement Type": "Movement",
    "Order Number": "Order No.",
    "Order Date": "Order Dt.",
    "Effective Date": "Effective Dt.",
    "Relieving Date": "Relieving Dt.",
    "Joining Date": "Joining Dt.",
    "Charge Assumed": "Charge Date",
    "Designation": "Desig.",
    "Issuing Authority": "Authority",
    "Start Date": "Start Dt.",
    "End Date": "End Dt.",
    "Number of Days": "Days",
    "Recorded Date": "Recorded Dt.",
    "Employment Type": "Employment",
    "First Appointment": "First Appt.",
    "Date of Birth": "DOB",
    "First Entry in Government Service": "Govt Entry",
    "First Entry in Judiciary": "Judiciary Entry",
    "Current Post Date": "Post Dt.",
    "Promotion Date": "Promotion Dt.",
    "Retirement Date": "Retire Dt.",
    "Current Posting": "Posting",
    "Transfer Reason": "Reason",
    "Event Type": "Event",
    "Total Availed": "Availed",
}


NUMERIC_HEADERS = {
    "Sr.",
    "Rank",
    "BPS",
    "Year",
    "Days",
    "Merit",
    "Credit",
    "Debit",
    "Balance",
    "Entitlement",
    "Availed",
    "Remaining",
}


COLUMN_WIDTH_PROFILES = {
    "individual_posting_history": [24, 13, 13, 34, 16],
    "leave_summary": [18, 24, 24, 24],
    "leave_history": [6, 12, 12, 9, 24, 25, 12],
    "seniority_list": [3, 7, 10, 7, 5, 7, 3, 7.5, 7.5, 7.5, 7, 7.5, 7.5, 5, 8.5],
    "service_records": [14, 5, 13, 9, 12, 11, 7, 29],
    "service_events": [8, 10, 13, 9, 12, 5, 14, 23, 6],
    "posting_transfer_order": [4, 16, 16, 13, 16, 10, 10, 15],
    "posting_transfer_followup": [5, 10, 10, 10, 12, 5, 21, 8, 19],
    "leave_ledger": [10, 11, 8, 8, 8, 17, 38],
}


def _base_document(title: str, generated_at, body: str) -> str:
    orientation = "landscape" if _requires_landscape(body) else "portrait"
    return f"""
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="report-orientation" content="{orientation}">
<style>{REPORT_CSS}</style>
</head>
<body class="report-{orientation}">
<div class="header">
  <div class="court">DISTRICT COURT ORAKZAI</div>
  <div class="system">HUMAN RESOURCE MANAGEMENT SYSTEM</div>
  <div class="title">{safe_text(title)}</div>
  <div class="meta">Generated: {report_date(generated_at)}</div>
</div>
{body}
<div class="footer">Official HR record. Generated by District Court Orakzai HRMS.</div>
</body>
</html>
"""


def _requires_landscape(body: str) -> bool:
    return (
        'data-report-landscape="true"' in body
        or 'name="report-orientation" content="landscape"' in body
    )


def _detail_table(rows: list[tuple[str, object]]) -> str:
    cells = []
    for label, value in rows:
        cells.append(
            f'<tr><td class="label">{safe_text(label)}</td><td>{_value(value)}</td></tr>'
        )
    return f"<table>{''.join(cells)}</table>"


def _data_table(
    headers: list[str],
    rows: list[list[object]],
    *,
    profile: str | None = None,
    landscape: bool = False,
) -> str:
    return build_professional_table(rows, headers, profile=profile, landscape=landscape)


def build_professional_table(
    data: list[list[object]],
    columns: list[str],
    widths: list[float] | None = None,
    *,
    profile: str | None = None,
    landscape: bool = False,
    compact: bool | None = None,
    empty_message: str = "No applicable records found.",
) -> str:
    column_widths = _column_widths(columns, widths, profile)
    report_landscape = landscape or len(columns) > WIDE_COLUMN_THRESHOLD
    use_compact = len(columns) > 6 if compact is None else compact
    table_size_class = "compact" if use_compact else "standard"
    base_table_attrs = [
        'width="100%"',
        f'class="report-table professional-table {table_size_class}"',
        f'data-columns="{len(columns)}"',
    ]
    if report_landscape:
        base_table_attrs.append('data-report-landscape="true"')

    row_chunks = _table_row_chunks(
        data,
        _rows_per_repeated_header_table(len(columns), use_compact),
    )
    return "".join(
        _render_professional_table(
            chunk,
            columns,
            column_widths,
            base_table_attrs,
            empty_message,
            page_break_before=index > 0,
        )
        for index, chunk in enumerate(row_chunks)
    )


def _render_professional_table(
    data: list[list[object]],
    columns: list[str],
    column_widths: list[float],
    base_table_attrs: list[str],
    empty_message: str,
    *,
    page_break_before: bool = False,
) -> str:
    table_attrs = list(base_table_attrs)
    if page_break_before:
        table_attrs.append('style="page-break-before: always;"')

    colgroup_html = "".join(
        f'<col width="{width:.2f}%" style="width: {width:.2f}%;">'
        for width in column_widths
    )
    header_html = "".join(
        _header_cell(header, column_widths[index])
        for index, header in enumerate(columns)
    )
    row_html = []
    for index, row in enumerate(data, start=1):
        row_class = ' class="alt"' if index % 2 == 0 else ""
        row_values = _fit_row_to_columns(row, len(columns))
        row_html.append(
            f"<tr{row_class}>"
            + "".join(
                (
                    f'<td class="{_cell_class(columns[col_index])}" '
                    f'width="{column_widths[col_index]:.2f}%" '
                    f'style="width: {column_widths[col_index]:.2f}%; '
                    'border: 1px solid #cbd5e1;">'
                    f"{_value(value)}</td>"
                )
                for col_index, value in enumerate(row_values)
            )
            + "</tr>"
        )
    if not data:
        row_html.append(
            f'<tr><td class="empty-table" colspan="{len(columns)}">'
            f"{safe_text(empty_message)}</td></tr>"
        )
    return (
        f"<table {' '.join(table_attrs)}>"
        f"<colgroup>{colgroup_html}</colgroup>"
        f"<thead><tr>{header_html}</tr></thead>"
        f"<tbody>{''.join(row_html)}</tbody>"
        "</table>"
    )


def _table_row_chunks(
    data: list[list[object]],
    rows_per_chunk: int,
) -> list[list[list[object]]]:
    if not data:
        return [[]]
    return [
        data[index : index + rows_per_chunk]
        for index in range(0, len(data), rows_per_chunk)
    ]


def _rows_per_repeated_header_table(column_count: int, compact: bool) -> int:
    if column_count >= 12:
        return 8
    if column_count >= 8:
        return 10
    if compact:
        return 14
    return 18


def _column_widths(
    columns: list[str],
    widths: list[float] | None = None,
    profile: str | None = None,
) -> list[float]:
    selected_widths = widths
    if selected_widths is None and profile:
        selected_widths = COLUMN_WIDTH_PROFILES.get(profile)
    if not selected_widths or len(selected_widths) != len(columns):
        selected_widths = [1.0 for _ in columns]

    total = sum(max(width, 0) for width in selected_widths) or 1.0
    return [(max(width, 0) / total) * 100 for width in selected_widths]


def _fit_row_to_columns(row: list[object], column_count: int) -> list[object]:
    fitted = list(row[:column_count])
    if len(fitted) < column_count:
        fitted.extend("" for _ in range(column_count - len(fitted)))
    return fitted


def _header_cell(header: str, width: float) -> str:
    label = HEADER_ALIASES.get(header, header)
    parts = label.split()
    rendered = "<br>".join(safe_text(part) for part in parts) if parts else "—"
    return (
        f'<th width="{width:.2f}%" '
        f'style="width: {width:.2f}%; border: 1px solid #9ca3af;">'
        f"{rendered}</th>"
    )


def _cell_class(header: str) -> str:
    label = HEADER_ALIASES.get(header, header)
    if label in NUMERIC_HEADERS:
        return "number"
    return "text"


def _value(value) -> str:
    if hasattr(value, "strftime"):
        return _allow_value_wrap(report_date(value))
    return _allow_value_wrap(safe_text(value))


def _allow_value_wrap(value: str) -> str:
    return (
        value.replace("/", "/<wbr>")
        .replace(",", ",<wbr>")
    )


def build_individual_profile_html(report: IndividualProfileReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Identity Details</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Father's Name", staff.get("father_name")),
    ("CNIC", staff.get("cnic")),
    ("Date of Birth", staff.get("date_of_birth")),
    ("Calculated Date of Retirement", staff.get("date_of_retirement")),
    ("Gender", staff.get("gender")),
    ("Religion", staff.get("religion")),
    ("Marital Status", staff.get("marital_status")),
    ("Qualification", staff.get("qualification")),
])}
<h2>Contact and Geographic Details</h2>
{_detail_table([
    ("Mobile Number", staff.get("mobile_number")),
    ("Email", staff.get("email")),
    ("Domicile", staff.get("domicile")),
    ("District", staff.get("district")),
    ("Tehsil", staff.get("tehsil")),
    ("Present Address", staff.get("present_address")),
    ("Permanent Address", staff.get("permanent_address")),
    ("Emergency Contact", staff.get("emergency_contact")),
])}
<h2>Current Service Details</h2>
{_detail_table([
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
    ("Employment Type", service.get("employment_type")),
    ("Employment Status", service.get("employment_status")),
    ("Date of First Appointment", service.get("date_first_appointment")),
    ("Date of Current Promotion", service.get("date_current_promotion")),
    ("Selection Merit Number", service.get("selection_merit_number")),
])}
<h2>Posting History</h2>
{_data_table(
    ["Station", "Start Date", "End Date", "Transfer Reason", "Current"],
    [
        [
            posting.get("station_name"),
            posting.get("start_date"),
            posting.get("end_date"),
            posting.get("transfer_reason"),
            "Yes" if posting.get("is_current") else "No",
        ]
        for posting in report.posting_history
    ],
    profile="individual_posting_history",
)}
<h2>Leave Summary</h2>
{_data_table(
    ["Year", "Entitlement", "Availed", "Remaining"],
    [
        [
            summary.get("leave_year"),
            summary.get("entitlement_days"),
            summary.get("availed_days"),
            summary.get("remaining_days"),
        ]
        for summary in report.leave_summaries
    ],
    profile="leave_summary",
)}
"""
    return _base_document("Individual Staff Profile", report.generated_at, body)


def build_leave_history_html(report: LeaveHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    selected = (
        "All Years" if report.selected_year is None else str(report.selected_year)
    )
    body = f"""
<h2>Staff Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
    ("Selected Year", selected),
])}
<h2>Leave Balance Summary</h2>
{_data_table(
    ["Year", "Entitlement", "Total Availed", "Remaining"],
    [
        [
            summary.get("leave_year"),
            summary.get("entitlement_days"),
            summary.get("availed_days"),
            summary.get("remaining_days"),
        ]
        for summary in report.summaries
    ],
    profile="leave_summary",
)}
<h2>Leave History</h2>
{_data_table(
    ["Serial", "Start Date", "End Date", "Number of Days", "Reason", "Remarks", "Recorded Date"],
    [
        [
            index,
            row.get("start_date"),
            row.get("end_date"),
            row.get("days_availed"),
            row.get("reason"),
            row.get("remarks"),
            row.get("created_at"),
        ]
        for index, row in enumerate(report.history, start=1)
    ],
    profile="leave_history",
)}
"""
    return _base_document("Leave History", report.generated_at, body)


def build_seniority_list_html(report: SeniorityListReport) -> str:
    body = f"""
<h2>Report Summary</h2>
{_detail_table([
    ("Designation", report.designation),
    ("Ranked Staff", len(report.ranked)),
    ("Generated Date", report.generated_at),
])}
<h2>Seniority Policy</h2>
<div class="policy">{safe_text(report.policy_summary)}</div>
<h2>Ranked Seniority Table</h2>
{_data_table(
    [
        "Rank",
        "Personal Number",
        "Full Name",
        "Father's Name",
        "Qualification",
        "Designation",
        "BPS",
        "Date of Birth",
        "First Entry in Government Service",
        "First Entry in Judiciary",
        "Current Post Date",
        "Promotion Date",
        "Retirement Date",
        "Current Posting",
        "Remarks",
    ],
    [
        [
            row.get("rank"),
            row.get("personal_number"),
            row.get("full_name"),
            row.get("father_name"),
            row.get("qualification"),
            row.get("designation"),
            row.get("bps"),
            row.get("date_of_birth"),
            row.get("first_government_entry"),
            row.get("first_judiciary_entry"),
            row.get("current_post_date"),
            row.get("promotion_date"),
            row.get("retirement_date"),
            row.get("current_posting"),
            row.get("remarks"),
        ]
        for row in report.ranked
    ],
    profile="seniority_list",
)}
"""
    return _base_document("Seniority List", report.generated_at, body)


def build_posting_history_html(report: PostingHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Employee Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
])}
<h2>Posting History</h2>
{_posting_table(report.posting_history)}
"""
    return _base_document("Complete Posting History", report.generated_at, body)


def build_transfer_history_html(report: TransferHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Employee Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
])}
<h2>Transfer History</h2>
{_posting_table(report.transfer_history)}
"""
    return _base_document("Complete Transfer History", report.generated_at, body)


def build_service_book_extract_html(report: ServiceBookExtractReport) -> str:
    staff = report.staff
    body = f"""
<h2>Employee Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Father's Name", staff.get("father_name")),
    ("Date of Birth", staff.get("date_of_birth")),
    ("Retirement Date", staff.get("date_of_retirement")),
])}
<h2>Service Records</h2>
{_data_table(
    ["Designation", "BPS", "Employment Type", "Status", "First Appointment", "Promotion", "Merit", "Remarks"],
    [
        [
            row.get("designation"),
            row.get("bps"),
            row.get("employment_type"),
            row.get("employment_status"),
            row.get("date_first_appointment"),
            row.get("date_current_promotion"),
            row.get("selection_merit_number"),
            row.get("remarks"),
        ]
        for row in report.service_records
    ],
    profile="service_records",
)}
<h2>Service Events</h2>
{_data_table(
    ["Date", "Event Type", "Order Number", "Order Date", "Designation", "BPS", "Station", "Description", "Status"],
    [
        [
            row.get("effective_date"),
            row.get("event_type"),
            row.get("order_number"),
            row.get("order_date"),
            row.get("new_designation") or row.get("previous_designation"),
            row.get("new_bps") or row.get("previous_bps"),
            row.get("station"),
            row.get("description"),
            "Cancelled" if row.get("is_cancelled") else "Active",
        ]
        for row in report.service_events
    ],
    profile="service_events",
)}
<h2>Posting and Transfer History</h2>
{_posting_table(report.posting_history)}
"""
    return _base_document("Service Book Extract", report.generated_at, body)


def build_employee_dossier_html(report: EmployeeDossierReport) -> str:
    profile = build_individual_profile_html(report.profile)
    service_book = build_service_book_extract_html(report.service_book)
    body = f"""
<h2>Dossier Sections</h2>
<div class="policy">This dossier combines profile, service-book, posting, leave and ledger information available in the HRMS.</div>
<h2>Profile</h2>
{profile}
<h2>Service Book</h2>
{service_book}
<h2>Leave History</h2>
{_data_table(
    ["Start Date", "End Date", "Days", "Reason", "Recorded Date"],
    [
        [
            row.get("start_date"),
            row.get("end_date"),
            row.get("days_availed"),
            row.get("reason"),
            row.get("created_at"),
        ]
        for row in report.leave_history
    ],
    profile="leave_history",
)}
<h2>Leave Ledger</h2>
{_data_table(
    ["Date", "Type", "Credit", "Debit", "Balance", "Reference", "Remarks"],
    [
        [
            row.get("entry_date"),
            row.get("entry_type"),
            row.get("credit_days"),
            row.get("debit_days"),
            row.get("balance_after"),
            row.get("reference"),
            row.get("remarks"),
        ]
        for row in report.leave_ledger
    ],
    profile="leave_ledger",
)}
"""
    return _base_document("Complete Employee Dossier", report.generated_at, body)


def _posting_table(rows: list[dict]) -> str:
    order_columns = [
        "Serial",
        "From Station",
        "To Station",
        "Movement Type",
        "Order Number",
        "Order Date",
        "Effective Date",
        "Issuing Authority",
    ]
    followup_columns = [
        "Serial",
        "Relieving Date",
        "Joining Date",
        "Charge Assumed",
        "Designation",
        "BPS",
        "Reason",
        "Status",
        "Remarks",
    ]
    order_rows = []
    followup_rows = []
    for index, row in enumerate(rows, start=1):
        order_rows.append(
            [
                index,
                row.get("from_station"),
                row.get("to_station") or row.get("station_name"),
                row.get("movement_type"),
                row.get("order_number"),
                row.get("order_date"),
                row.get("effective_date") or row.get("start_date"),
                row.get("issuing_authority"),
            ]
        )
        followup_rows.append(
            [
                index,
                row.get("relieving_date"),
                row.get("joining_date"),
                row.get("charge_assumed_date"),
                row.get("to_designation") or row.get("from_designation"),
                row.get("to_bps") or row.get("from_bps"),
                row.get("transfer_reason"),
                row.get("status") or ("Current" if row.get("is_current") else ""),
                row.get("remarks"),
            ]
        )

    return (
        "<h3>Posting / Transfer Order Details</h3>"
        + build_professional_table(
            order_rows,
            order_columns,
            profile="posting_transfer_order",
            landscape=True,
        )
        + "<h3>Relieving / Joining / Remarks Details</h3>"
        + build_professional_table(
            followup_rows,
            followup_columns,
            profile="posting_transfer_followup",
            landscape=True,
        )
    )
