from __future__ import annotations

from court_hrms.reporting.report_dtos import (
    EmployeeDossierReport,
    IndividualProfileReport,
    LeaveHistoryReport,
    PostingHistoryReport,
    SeniorityListReport,
    ServiceBookExtractReport,
    TransferHistoryReport,
)
from court_hrms.utils.report_utils import report_date, safe_text


REPORT_CSS = """
body { font-family: "Times New Roman", serif; font-size: 10pt; color: #111827; }
.header { text-align: center; border-bottom: 2px solid #0b1f3a; padding-bottom: 8px; margin-bottom: 12px; }
.court { font-size: 16pt; font-weight: bold; letter-spacing: 0; color: #0b1f3a; }
.system { font-size: 11pt; font-weight: bold; color: #374151; }
.title { font-size: 13pt; font-weight: bold; margin-top: 8px; }
.meta { font-size: 9pt; color: #4b5563; margin-top: 4px; }
h2 { font-size: 11pt; color: #0b1f3a; border-bottom: 1px solid #c9a227; margin: 14px 0 6px; }
table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
th { background: #0b1f3a; color: #ffffff; font-weight: bold; }
th, td { border: 1px solid #9ca3af; padding: 5px; vertical-align: top; }
.label { width: 24%; font-weight: bold; background: #f3f4f6; }
.footer { border-top: 1px solid #9ca3af; margin-top: 16px; padding-top: 6px; font-size: 9pt; color: #4b5563; text-align: center; }
.policy { border: 1px solid #9ca3af; padding: 6px; background: #f9fafb; }
"""


def _base_document(title: str, generated_at, body: str) -> str:
    return f"""
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>{REPORT_CSS}</style>
</head>
<body>
<div class="header">
  <div class="court">DISTRICT COURT ORAKZAI</div>
  <div class="system">HUMAN RESOURCE MANAGEMENT SYSTEM</div>
  <div class="title">{safe_text(title)}</div>
  <div class="meta">Generated: {report_date(generated_at)}</div>
</div>
{body}
<div class="footer">Official HR record. Generated by District Court Orakzai HRMS.</div>
</body>
</html>
"""


def _detail_table(rows: list[tuple[str, object]]) -> str:
    cells = []
    for label, value in rows:
        cells.append(
            f'<tr><td class="label">{safe_text(label)}</td><td>{_value(value)}</td></tr>'
        )
    return f"<table>{''.join(cells)}</table>"


def _data_table(headers: list[str], rows: list[list[object]]) -> str:
    header_html = "".join(f"<th>{safe_text(header)}</th>" for header in headers)
    row_html = []
    for row in rows:
        row_html.append(
            "<tr>" + "".join(f"<td>{_value(value)}</td>" for value in row) + "</tr>"
        )
    if not rows:
        row_html.append(
            f'<tr><td colspan="{len(headers)}">No applicable records found.</td></tr>'
        )
    return f"<table><thead><tr>{header_html}</tr></thead><tbody>{''.join(row_html)}</tbody></table>"


def _value(value) -> str:
    if hasattr(value, "strftime"):
        return report_date(value)
    return safe_text(value)


def build_individual_profile_html(report: IndividualProfileReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Identity Details</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Father's Name", staff.get("father_name")),
    ("CNIC", staff.get("cnic")),
    ("Date of Birth", staff.get("date_of_birth")),
    ("Calculated Date of Retirement", staff.get("date_of_retirement")),
    ("Gender", staff.get("gender")),
    ("Religion", staff.get("religion")),
    ("Marital Status", staff.get("marital_status")),
    ("Qualification", staff.get("qualification")),
])}
<h2>Contact and Geographic Details</h2>
{_detail_table([
    ("Mobile Number", staff.get("mobile_number")),
    ("Email", staff.get("email")),
    ("Domicile", staff.get("domicile")),
    ("District", staff.get("district")),
    ("Tehsil", staff.get("tehsil")),
    ("Present Address", staff.get("present_address")),
    ("Permanent Address", staff.get("permanent_address")),
    ("Emergency Contact", staff.get("emergency_contact")),
])}
<h2>Current Service Details</h2>
{_detail_table([
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
    ("Employment Type", service.get("employment_type")),
    ("Employment Status", service.get("employment_status")),
    ("Date of First Appointment", service.get("date_first_appointment")),
    ("Date of Current Promotion", service.get("date_current_promotion")),
    ("Selection Merit Number", service.get("selection_merit_number")),
])}
<h2>Posting History</h2>
{_data_table(
    ["Station", "Start Date", "End Date", "Transfer Reason", "Current"],
    [
        [
            posting.get("station_name"),
            posting.get("start_date"),
            posting.get("end_date"),
            posting.get("transfer_reason"),
            "Yes" if posting.get("is_current") else "No",
        ]
        for posting in report.posting_history
    ],
)}
<h2>Leave Summary</h2>
{_data_table(
    ["Year", "Entitlement", "Availed", "Remaining"],
    [
        [
            summary.get("leave_year"),
            summary.get("entitlement_days"),
            summary.get("availed_days"),
            summary.get("remaining_days"),
        ]
        for summary in report.leave_summaries
    ],
)}
"""
    return _base_document("Individual Staff Profile", report.generated_at, body)


def build_leave_history_html(report: LeaveHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    selected = (
        "All Years" if report.selected_year is None else str(report.selected_year)
    )
    body = f"""
<h2>Staff Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
    ("Selected Year", selected),
])}
<h2>Leave Balance Summary</h2>
{_data_table(
    ["Year", "Entitlement", "Total Availed", "Remaining"],
    [
        [
            summary.get("leave_year"),
            summary.get("entitlement_days"),
            summary.get("availed_days"),
            summary.get("remaining_days"),
        ]
        for summary in report.summaries
    ],
)}
<h2>Leave History</h2>
{_data_table(
    ["Serial", "Start Date", "End Date", "Number of Days", "Reason", "Remarks", "Recorded Date"],
    [
        [
            index,
            row.get("start_date"),
            row.get("end_date"),
            row.get("days_availed"),
            row.get("reason"),
            row.get("remarks"),
            row.get("created_at"),
        ]
        for index, row in enumerate(report.history, start=1)
    ],
)}
"""
    return _base_document("Leave History", report.generated_at, body)


def build_seniority_list_html(report: SeniorityListReport) -> str:
    body = f"""
<h2>Report Summary</h2>
{_detail_table([
    ("Designation", report.designation),
    ("Ranked Staff", len(report.ranked)),
    ("Generated Date", report.generated_at),
])}
<h2>Seniority Policy</h2>
<div class="policy">{safe_text(report.policy_summary)}</div>
<h2>Ranked Seniority Table</h2>
{_data_table(
    [
        "Rank",
        "Personal Number",
        "Full Name",
        "Father's Name",
        "Qualification",
        "Designation",
        "BPS",
        "Date of Birth",
        "First Entry in Government Service",
        "First Entry in Judiciary",
        "Current Post Date",
        "Promotion Date",
        "Retirement Date",
        "Current Posting",
        "Remarks",
    ],
    [
        [
            row.get("rank"),
            row.get("personal_number"),
            row.get("full_name"),
            row.get("father_name"),
            row.get("qualification"),
            row.get("designation"),
            row.get("bps"),
            row.get("date_of_birth"),
            row.get("first_government_entry"),
            row.get("first_judiciary_entry"),
            row.get("current_post_date"),
            row.get("promotion_date"),
            row.get("retirement_date"),
            row.get("current_posting"),
            row.get("remarks"),
        ]
        for row in report.ranked
    ],
)}
"""
    return _base_document("Seniority List", report.generated_at, body)


def build_posting_history_html(report: PostingHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Employee Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
])}
<h2>Posting History</h2>
{_posting_table(report.posting_history)}
"""
    return _base_document("Complete Posting History", report.generated_at, body)


def build_transfer_history_html(report: TransferHistoryReport) -> str:
    staff = report.staff
    service = report.service_record or {}
    body = f"""
<h2>Employee Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Designation", service.get("designation")),
    ("BPS", service.get("bps")),
])}
<h2>Transfer History</h2>
{_posting_table(report.transfer_history)}
"""
    return _base_document("Complete Transfer History", report.generated_at, body)


def build_service_book_extract_html(report: ServiceBookExtractReport) -> str:
    staff = report.staff
    body = f"""
<h2>Employee Identification</h2>
{_detail_table([
    ("Personal Number", staff.get("personal_number")),
    ("Full Name", staff.get("full_name")),
    ("Father's Name", staff.get("father_name")),
    ("Date of Birth", staff.get("date_of_birth")),
    ("Retirement Date", staff.get("date_of_retirement")),
])}
<h2>Service Records</h2>
{_data_table(
    ["Designation", "BPS", "Employment Type", "Status", "First Appointment", "Promotion", "Merit", "Remarks"],
    [
        [
            row.get("designation"),
            row.get("bps"),
            row.get("employment_type"),
            row.get("employment_status"),
            row.get("date_first_appointment"),
            row.get("date_current_promotion"),
            row.get("selection_merit_number"),
            row.get("remarks"),
        ]
        for row in report.service_records
    ],
)}
<h2>Service Events</h2>
{_data_table(
    ["Date", "Event Type", "Order Number", "Order Date", "Designation", "BPS", "Station", "Description", "Status"],
    [
        [
            row.get("effective_date"),
            row.get("event_type"),
            row.get("order_number"),
            row.get("order_date"),
            row.get("new_designation") or row.get("previous_designation"),
            row.get("new_bps") or row.get("previous_bps"),
            row.get("station"),
            row.get("description"),
            "Cancelled" if row.get("is_cancelled") else "Active",
        ]
        for row in report.service_events
    ],
)}
<h2>Posting and Transfer History</h2>
{_posting_table(report.posting_history)}
"""
    return _base_document("Service Book Extract", report.generated_at, body)


def build_employee_dossier_html(report: EmployeeDossierReport) -> str:
    profile = build_individual_profile_html(report.profile)
    service_book = build_service_book_extract_html(report.service_book)
    body = f"""
<h2>Dossier Sections</h2>
<div class="policy">This dossier combines profile, service-book, posting, leave and ledger information available in the HRMS.</div>
<h2>Profile</h2>
{profile}
<h2>Service Book</h2>
{service_book}
<h2>Leave History</h2>
{_data_table(
    ["Start Date", "End Date", "Days", "Reason", "Recorded Date"],
    [
        [
            row.get("start_date"),
            row.get("end_date"),
            row.get("days_availed"),
            row.get("reason"),
            row.get("created_at"),
        ]
        for row in report.leave_history
    ],
)}
<h2>Leave Ledger</h2>
{_data_table(
    ["Date", "Type", "Credit", "Debit", "Balance", "Reference", "Remarks"],
    [
        [
            row.get("entry_date"),
            row.get("entry_type"),
            row.get("credit_days"),
            row.get("debit_days"),
            row.get("balance_after"),
            row.get("reference"),
            row.get("remarks"),
        ]
        for row in report.leave_ledger
    ],
)}
"""
    return _base_document("Complete Employee Dossier", report.generated_at, body)


def _posting_table(rows: list[dict]) -> str:
    return _data_table(
        [
            "Serial",
            "From Station",
            "To Station",
            "Movement Type",
            "Order Number",
            "Order Date",
            "Effective Date",
            "Relieving Date",
            "Joining Date",
            "Charge Assumed",
            "Designation",
            "BPS",
            "Issuing Authority",
            "Reason",
            "Status",
            "Remarks",
        ],
        [
            [
                index,
                row.get("from_station"),
                row.get("to_station") or row.get("station_name"),
                row.get("movement_type"),
                row.get("order_number"),
                row.get("order_date"),
                row.get("effective_date") or row.get("start_date"),
                row.get("relieving_date"),
                row.get("joining_date"),
                row.get("charge_assumed_date"),
                row.get("to_designation") or row.get("from_designation"),
                row.get("to_bps") or row.get("from_bps"),
                row.get("issuing_authority"),
                row.get("transfer_reason"),
                row.get("status") or ("Current" if row.get("is_current") else ""),
                row.get("remarks"),
            ]
            for index, row in enumerate(rows, start=1)
        ],
    )
